# Generated by Django 3.2.8 on 2021-10-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_process_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='parts',
            field=models.ManyToManyField(blank=True, to='core.Part', verbose_name='partes'),
        ),
    ]
